/**
 * Master Data Engine for 120-Day Cloud Security Engineer Transition Playbook
 * COMPLETE 26 SECTIONS AUDIT FOR SCOTT DUFFY AZ-104 + FULL SECTIONS FOR AZ-500 & SC-100
 */

export const COURSE_MODULES = [
  {
    id: 1,
    code: "AZ-104",
    instructor: "Scott Duffy",
    title: "Course 1: Scott Duffy - AZ-104 Azure Administrator (Udemy)",
    daysRange: "Days 1 – 15 (Weeks 1–2)",
    status: "Owned",
    totalSections: 26,
    focus: "Complete 26 Sections of Scott Duffy AZ-104 Curriculum",
    sections: [
      { num: 1, title: "Section 1: Course Introduction & Blueprint Strategy", estHours: "0.5h" },
      { num: 2, title: "Section 2: Prerequisites & Setting Up Your Azure Subscription", estHours: "0.5h" },
      { num: 3, title: "Section 3: Azure Global Infrastructure (Regions, Zones & Availability Sets)", estHours: "1.0h" },
      { num: 4, title: "Section 4: Managing Azure Subscriptions, Governance & Cost Management", estHours: "1.0h" },
      { num: 5, title: "Section 5: Resource Groups & Managing Azure Resources", estHours: "0.5h" },
      { num: 6, title: "Section 6: Resource Locks, Tagging & Organization", estHours: "0.5h" },
      { num: 7, title: "Section 7: Azure Policy Definitions & Compliance Guardrails", estHours: "1.0h" },
      { num: 8, title: "Section 8: Azure Active Directory / Entra ID Core Concepts", estHours: "1.0h" },
      { num: 9, title: "Section 9: Managing Users, Groups & Administrative Units in Entra ID", estHours: "1.5h" },
      { num: 10, title: "Section 10: Azure Role-Based Access Control (RBAC) & Custom Roles", estHours: "1.0h" },
      { num: 11, title: "Section 11: Virtual Networks (VNets), Subnets & IP Addressing", estHours: "2.5h" },
      { num: 12, title: "Section 12: Network Security Groups (NSGs) & Application Security Groups (ASGs)", estHours: "1.5h" },
      { num: 13, title: "Section 13: User Defined Routes (UDR) & Custom Routing", estHours: "1.5h" },
      { num: 14, title: "Section 14: Virtual Network Peering & Gateway Transit", estHours: "1.0h" },
      { num: 15, title: "Section 15: Azure Bastion Host & Secure Remote Management", estHours: "0.5h" },
      { num: 16, title: "Section 16: Azure DNS & Private DNS Zones", estHours: "1.0h" },
      { num: 17, title: "Section 17: Azure Storage Accounts & Storage Explorer", estHours: "1.0h" },
      { num: 18, title: "Section 18: Storage Security, Shared Access Signatures (SAS) & Storage Firewalls", estHours: "1.5h" },
      { num: 19, title: "Section 19: Azure Files, File Sync & Storage Redundancy", estHours: "1.0h" },
      { num: 20, title: "Section 20: Provisioning & Managing Virtual Machines (Linux & Windows)", estHours: "2.0h" },
      { num: 21, title: "Section 21: VM Extensions, Automated Deployment & Custom Images", estHours: "1.0h" },
      { num: 22, title: "Section 22: Virtual Machine Scale Sets (VMSS) & High Availability", estHours: "1.5h" },
      { num: 23, title: "Section 23: Azure Standard Load Balancer & Traffic Routing", estHours: "1.5h" },
      { num: 24, title: "Section 24: Azure Application Gateway & Layer 7 Load Balancing", estHours: "2.0h" },
      { num: 25, title: "Section 25: Azure Monitor, Diagnostic Settings, Metrics & Alerts", estHours: "1.5h" },
      { num: 26, title: "Section 26: AZ-104 Exam Review, Practice Exam & Project 1 Deployment", estHours: "2.5h" }
    ]
  },
  {
    id: 2,
    code: "AZ-500",
    instructor: "Alan Rodrigues",
    title: "Course 2: Alan Rodrigues - AZ-500 Azure Security Engineer (Udemy)",
    daysRange: "Days 16 – 60 (Weeks 3–8)",
    status: "Owned",
    totalSections: 21,
    focus: "Complete 21 Sections of Alan Rodrigues AZ-500 Curriculum",
    sections: [
      { num: 1, title: "Section 1: Course Overview & Azure Security Fundamentals", estHours: "0.5h" },
      { num: 2, title: "Section 2: Entra ID App Registrations & Service Principals", estHours: "1.5h" },
      { num: 3, title: "Section 3: Configure Conditional Access Policies, MFA & FIDO2 Passkeys", estHours: "2.0h" },
      { num: 4, title: "Section 4: Configure Entra Privileged Identity Management (PIM) & Access Reviews", estHours: "1.5h" },
      { num: 5, title: "Section 5: Configure Managed Identities & Workload Identities", estHours: "1.5h" },
      { num: 6, title: "Section 6: Configure Azure Firewall Premium & TLS Inspection", estHours: "2.5h" },
      { num: 7, title: "Section 7: Configure Application Gateway WAF v2 (OWASP Rules)", estHours: "2.0h" },
      { num: 8, title: "Section 8: Configure Network Microsegmentation, NSGs & UDR Next Hop", estHours: "1.5h" },
      { num: 9, title: "Section 9: Configure Private Endpoints & Private Link DNS", estHours: "2.0h" },
      { num: 10, title: "Section 10: Secure Azure Storage Accounts & Disable Shared Keys", estHours: "1.5h" },
      { num: 11, title: "Section 11: Configure Azure Key Vault (RBAC Mode & Soft Delete)", estHours: "1.5h" },
      { num: 12, title: "Section 12: Configure Disk & Data Encryption (ADE, SSE, CMK)", estHours: "1.5h" },
      { num: 13, title: "Section 13: Configure Azure SQL Security (TDE, Dynamic Masking)", estHours: "1.5h" },
      { num: 14, title: "Section 14: Configure Defender for Cloud CSPM & Secure Score", estHours: "1.5h" },
      { num: 15, title: "Section 15: Configure Defender for Workloads (Defender for Servers & Containers)", estHours: "1.5h" },
      { num: 16, title: "Section 16: Configure Microsoft Sentinel Log Ingestion & LAW", estHours: "1.5h" },
      { num: 17, title: "Section 17: Master KQL Syntax & Log Analytics Queries", estHours: "2.5h" },
      { num: 18, title: "Section 18: Configure Data Collection Rules (DCR) & AMA Agent", estHours: "1.5h" },
      { num: 19, title: "Section 19: Configure Sentinel Analytic Rules & Incident Triage", estHours: "1.5h" },
      { num: 20, title: "Section 20: Configure Sentinel Automation Rules & Logic Apps SOAR Playbooks", estHours: "2.0h" },
      { num: 21, title: "Section 21: AZ-500 Practice Exams & Certification Exam Milestone", estHours: "3.0h" }
    ]
  },
  {
    id: 3,
    code: "SC-100",
    instructor: "Alan Rodrigues",
    title: "Course 3: Alan Rodrigues - SC-100 Cybersecurity Architect (Udemy)",
    daysRange: "Days 61 – 80 (Weeks 9–11)",
    status: "Owned",
    totalSections: 8,
    focus: "Complete 8 Sections of Alan Rodrigues SC-100 Curriculum",
    sections: [
      { num: 1, title: "Section 1: Introduction to Cybersecurity Architecture", estHours: "0.5h" },
      { num: 2, title: "Section 2: Design a Zero Trust Strategy (NIST SP 800-207)", estHours: "2.0h" },
      { num: 3, title: "Section 3: Design Enterprise Landing Zones (ALZ) & Management Groups", estHours: "2.0h" },
      { num: 4, title: "Section 4: Design Azure Policy-as-Code Guardrails", estHours: "1.5h" },
      { num: 5, title: "Section 5: Design Ransomware Defense & WORM Storage Immutability", estHours: "1.5h" },
      { num: 6, title: "Section 6: Design Cloud Incident Response & Auto-Isolation Workflows", estHours: "2.0h" },
      { num: 7, title: "Section 7: Design Multi-Cloud & Hybrid Security Architecture", estHours: "1.5h" },
      { num: 8, title: "Section 8: SC-100 Architecture Case Studies & Final Exam Milestone", estHours: "3.0h" }
    ]
  },
  {
    id: 4,
    code: "AWS-SEC",
    instructor: "Stephane Maarek",
    title: "Course 4: Stephane Maarek - AWS Security Specialty (Udemy)",
    daysRange: "Days 81 – 95 (Weeks 11–13)",
    status: "Recommended Gap-Fill",
    totalSections: 8,
    focus: "AWS Security Core (Sections 1 through 8)",
    sections: [
      { num: 1, title: "Section 1: AWS IAM Advanced Policies & Evaluation Logic", estHours: "2.0h" },
      { num: 2, title: "Section 2: AWS STS AssumeRole & Cross-Account ExternalId Validation", estHours: "2.0h" },
      { num: 3, title: "Section 3: AWS VPC Endpoints (Interface & Gateway) & Endpoint Policies", estHours: "2.0h" },
      { num: 4, title: "Section 4: AWS KMS Envelope Encryption & CMK Key Policies", estHours: "1.5h" },
      { num: 5, title: "Section 5: AWS GuardDuty ML Threat Detection Engine", estHours: "1.5h" },
      { num: 6, title: "Section 6: AWS Security Hub CIS Benchmarks Aggregation", estHours: "1.5h" },
      { num: 7, title: "Section 7: AWS CloudTrail Audit Logging & Digest Validation", estHours: "1.5h" },
      { num: 8, title: "Section 8: AWS Systems Manager (SSM) Session Manager", estHours: "1.5h" }
    ]
  },
  {
    id: 5,
    code: "TERRAFORM",
    instructor: "Zeal Vora",
    title: "Course 5: Zeal Vora - HashiCorp Terraform Associate (Udemy)",
    daysRange: "Days 96 – 105 (Weeks 13–14)",
    status: "Recommended Gap-Fill",
    totalSections: 6,
    focus: "Terraform IaC Security (Sections 1 through 6)",
    sections: [
      { num: 1, title: "Section 1: Terraform Infrastructure as Code Core Fundamentals", estHours: "1.5h" },
      { num: 2, title: "Section 2: Terraform State Encryption & Remote Backend Locking", estHours: "2.0h" },
      { num: 3, title: "Section 3: Reusable Terraform Security Modules Structure", estHours: "2.0h" },
      { num: 4, title: "Section 4: Checkov & Tfsec Static IaC Security Analysis", estHours: "1.5h" },
      { num: 5, title: "Section 5: GitHub Actions CI/CD Pipeline Integration", estHours: "2.0h" },
      { num: 6, title: "Section 6: Automated Dynamic Secret Rotation Pipelines", estHours: "2.0h" }
    ]
  },
  {
    id: 6,
    code: "CKS",
    instructor: "Mumshad Mannambeth",
    title: "Course 6: Mumshad Mannambeth - CKS Kubernetes Security Specialist (Udemy)",
    daysRange: "Days 106 – 120 (Weeks 15–16)",
    status: "Recommended Gap-Fill",
    totalSections: 6,
    focus: "Kubernetes & Container Security (Sections 1 through 6)",
    sections: [
      { num: 1, title: "Section 1: Hardening Docker Containers & Distroless Base Images", estHours: "1.5h" },
      { num: 2, title: "Section 2: Kubernetes Pod Security Admission (PSA) Restricted Profile", estHours: "2.0h" },
      { num: 3, title: "Section 3: Kubernetes NetworkPolicies & Microsegmentation", estHours: "2.0h" },
      { num: 4, title: "Section 4: Falco eBPF Runtime Threat Detection", estHours: "2.0h" },
      { num: 5, title: "Section 5: Trivy Image Scanning & Sigstore Cosign Container Signing", estHours: "2.0h" },
      { num: 6, title: "Section 6: SC-100 Final Exam Review & 15 Repos Launch", estHours: "3.0h" }
    ]
  }
];

export const ACHIEVEMENTS_LIST = [
  { id: "streak_3", icon: "🔥", title: "3-Day Fire", desc: "Maintained a 3-day active study streak!", xp: 100 },
  { id: "streak_7", icon: "⚡", title: "7-Day Streak Master", desc: "Maintained a 7-day active study streak!", xp: 300 },
  { id: "project_1", icon: "🛡️", title: "Perimeter Boss", desc: "Deployed Project 1: Azure Hub-and-Spoke Secure Network Perimeter!", xp: 250 },
  { id: "project_5", icon: "🔮", title: "KQL Wizard", desc: "Deployed Project 5: Microsoft Sentinel SIEM & SOAR Engine!", xp: 250 },
  { id: "cert_az500", icon: "🏆", title: "Azure Security Associate", desc: "Passed the AZ-500 Certification Exam!", xp: 500 },
  { id: "cert_sc100", icon: "👑", title: "Cybersecurity Architect", desc: "Passed the SC-100 Expert Certification Exam!", xp: 1000 },
  { id: "level_5", icon: "🚀", title: "Cloud Sec Engineer", desc: "Reached Engineer Level 5!", xp: 500 }
];

export const CERTIFICATIONS_LIST = [
  {
    id: "az-500",
    code: "AZ-500",
    title: "Microsoft Certified: Azure Security Engineer Associate",
    targetDay: 60,
    targetMonth: "End of Course 2 (Day 60)",
    priority: "P0 - Mandatory Baseline",
    passingScore: "700 / 1000",
    udemyCourse: "Alan Rodrigues AZ-500 Course (Udemy)",
    description: "Primary technical certification validating Azure network security, Entra ID IAM, Key Vault data protection, Defender for Cloud, and Sentinel KQL security operations.",
    domains: [
      { name: "Manage Identity and Access (Entra ID, PIM, CA)", weight: "25-30%" },
      { name: "Secure Networking (VNets, Firewall, WAF, Private Link)", weight: "20-25%" },
      { name: "Secure Compute, Storage & Databases (Key Vault, CMK)", weight: "20-25%" },
      { name: "Manage Security Operations (Sentinel KQL, MDC)", weight: "25-30%" }
    ]
  },
  {
    id: "sc-100",
    code: "SC-100",
    title: "Microsoft Certified: Cybersecurity Architect Expert",
    targetDay: 120,
    targetMonth: "End of Course 6 (Day 120)",
    priority: "P0 - High-Salary Booster (₹35L+)",
    passingScore: "700 / 1000",
    udemyCourse: "Alan Rodrigues SC-100 Course (Udemy)",
    description: "Pinnacle Microsoft architecture certification validating Zero Trust strategy, enterprise Landing Zones, threat response, and multi-cloud security governance.",
    domains: [
      { name: "Design a Zero Trust Strategy & Architecture", weight: "30-35%" },
      { name: "Evaluate GRC & Security Operations Strategies", weight: "20-25%" },
      { name: "Design Security for Infrastructure & Data", weight: "20-25%" },
      { name: "Design Security for Applications & Workloads", weight: "20-25%" }
    ]
  }
];

export const DAYS_CURRICULUM = [
  // =========================================================================
  // COURSE 1: SCOTT DUFFY - AZ-104 (ALL 26 SECTIONS AUDITED & MAPPED ACROSS DAYS 1-15)
  // =========================================================================
  {
    day: 1,
    week: 1,
    courseId: 1,
    courseCode: "AZ-104",
    courseTitle: "Scott Duffy AZ-104",
    title: "Scott Duffy AZ-104: Section 1, 2 & 3",
    hours: 1.5,
    udemyRef: "Scott Duffy AZ-104 (Section 1: Intro, Section 2: Prerequisites & Section 3: Global Infrastructure)",
    topic: "Subscriptions, Regions, Availability Zones & Availability Sets.",
    outcome: "Understand Azure infrastructure boundaries.",
    lab: "Provision Resource Group hierarchy with custom tags via Azure CLI.",
    revision: "Management group inheritance rules.",
    category: "Azure Admin"
  },
  {
    day: 2,
    week: 1,
    courseId: 1,
    courseCode: "AZ-104",
    courseTitle: "Scott Duffy AZ-104",
    title: "Scott Duffy AZ-104: Section 4 & 5",
    hours: 1.5,
    udemyRef: "Scott Duffy AZ-104 (Section 4: Managing Subscriptions & Section 5: Resource Groups)",
    topic: "Subscriptions, Resource Groups, Cost Management, Billing Alerts.",
    outcome: "Organize Azure cloud resources and budgets.",
    lab: "Configure Cost Management budget alert in Azure Portal.",
    revision: "Billing scope hierarchy.",
    category: "Governance"
  },
  {
    day: 3,
    week: 1,
    courseId: 1,
    courseCode: "AZ-104",
    courseTitle: "Scott Duffy AZ-104",
    title: "Scott Duffy AZ-104: Section 6 & 7",
    hours: 1.5,
    udemyRef: "Scott Duffy AZ-104 (Section 6: Resource Locks & Section 7: Azure Policy)",
    topic: "Resource Locks (CanNotDelete/ReadOnly), Azure Policy definitions, Initiatives.",
    outcome: "Configure subscription security guardrails.",
    lab: "Apply ReadOnly Resource Lock and test deletion block.",
    revision: "Policy evaluation cycles.",
    category: "Governance"
  },
  {
    day: 4,
    week: 1,
    courseId: 1,
    courseCode: "AZ-104",
    courseTitle: "Scott Duffy AZ-104",
    title: "Scott Duffy AZ-104: Section 8 & 9",
    hours: 2.0,
    udemyRef: "Scott Duffy AZ-104 (Section 8: Entra ID Core & Section 9: Managing Users & Groups)",
    topic: "Users, Security Groups, Dynamic Groups, Administrative Units, Custom Domains.",
    outcome: "Manage identity directory objects.",
    lab: "Create Dynamic Group based on Department tag.",
    revision: "Security Groups vs M365 Groups.",
    category: "IAM"
  },
  {
    day: 5,
    week: 1,
    courseId: 1,
    courseCode: "AZ-104",
    courseTitle: "Scott Duffy AZ-104",
    title: "Scott Duffy AZ-104: Section 10",
    hours: 1.5,
    udemyRef: "Scott Duffy AZ-104 (Section 10: Azure RBAC & Custom Roles)",
    topic: "Built-in Roles, Role Assignments, Custom JSON Definitions.",
    outcome: "Implement least-privilege control plane access.",
    lab: "Create custom JSON role for Virtual Machine Operator.",
    revision: "RBAC inheritance scope.",
    category: "IAM"
  },
  {
    day: 6,
    week: 1,
    courseId: 1,
    courseCode: "AZ-104",
    courseTitle: "Scott Duffy AZ-104",
    title: "Scott Duffy AZ-104: Section 11",
    hours: 2.5,
    udemyRef: "Scott Duffy AZ-104 (Section 11: Virtual Networks, Subnets & IP Addressing)",
    topic: "IPv4 CIDR blocks, VNet creation, Subnets, System Default Routes.",
    outcome: "Design enterprise VNet address spaces.",
    lab: "Create Hub VNet (10.0.0.0/16) and 2 Spoke VNets via Azure CLI.",
    revision: "Azure reserved IP addresses per subnet (5 reserved IPs).",
    category: "Networking"
  },
  {
    day: 7,
    week: 1,
    courseId: 1,
    courseCode: "AZ-104",
    courseTitle: "Scott Duffy AZ-104",
    title: "Scott Duffy AZ-104: Section 12 & 13",
    hours: 2.5,
    udemyRef: "Scott Duffy AZ-104 (Section 12: NSGs & ASGs & Section 13: User Defined Routes - UDR)",
    topic: "NSG Rules, ASGs, System Routes vs Custom Routes, Next Hop types.",
    outcome: "Configure network microsegmentation and forced egress.",
    lab: "Configure Route Table with 0.0.0.0/0 route to VirtualAppliance.",
    revision: "Longest Prefix Match routing algorithm.",
    category: "Networking"
  },
  {
    day: 8,
    week: 2,
    courseId: 1,
    courseCode: "AZ-104",
    courseTitle: "Scott Duffy AZ-104",
    title: "Scott Duffy AZ-104: Section 14, 15 & 16",
    hours: 2.0,
    udemyRef: "Scott Duffy AZ-104 (Section 14: VNet Peering, Sec 15: Bastion Host, Sec 16: Azure DNS)",
    topic: "VNet Peering, Gateway Transit, Azure Bastion, Private DNS Zones.",
    outcome: "Connect VNets privately and secure admin SSH/RDP.",
    lab: "Establish bi-directional VNet peering between Hub and Spokes.",
    revision: "Gateway transit requirements.",
    category: "Networking"
  },
  {
    day: 9,
    week: 2,
    courseId: 1,
    courseCode: "AZ-104",
    courseTitle: "Scott Duffy AZ-104",
    title: "Scott Duffy AZ-104: Section 17 & 18",
    hours: 2.0,
    udemyRef: "Scott Duffy AZ-104 (Section 17: Storage Accounts & Sec 18: Storage Security & SAS)",
    topic: "Blob Containers, Storage Accounts, SAS Tokens, Storage Firewalls.",
    outcome: "Configure secure blob storage.",
    lab: "Provision Storage Account, create SAS token, test access.",
    revision: "Account SAS vs Service SAS.",
    category: "Storage"
  },
  {
    day: 10,
    week: 2,
    courseId: 1,
    courseCode: "AZ-104",
    courseTitle: "Scott Duffy AZ-104",
    title: "Scott Duffy AZ-104: Section 19",
    hours: 1.5,
    udemyRef: "Scott Duffy AZ-104 (Section 19: Azure Files, File Sync & Storage Redundancy)",
    topic: "Azure Files, SMB shares, Azure File Sync, LRS/ZRS/GRS redundancy.",
    outcome: "Implement enterprise file storage and backup.",
    lab: "Deploy Azure File Share with quota restrictions.",
    revision: "Storage replication modes.",
    category: "Storage"
  },
  {
    day: 11,
    week: 2,
    courseId: 1,
    courseCode: "AZ-104",
    courseTitle: "Scott Duffy AZ-104",
    title: "Scott Duffy AZ-104: Section 20 & 21",
    hours: 2.0,
    udemyRef: "Scott Duffy AZ-104 (Section 20: Provisioning VMs & Sec 21: VM Extensions)",
    topic: "VM Sizes, Disks, Managed Disks, Custom Images, VM Extensions.",
    outcome: "Deploy secure IaaS Linux/Windows compute.",
    lab: "Deploy Ubuntu VM with Managed Disk and Custom Script Extension.",
    revision: "Availability Zones vs Availability Sets.",
    category: "Compute"
  },
  {
    day: 12,
    week: 2,
    courseId: 1,
    courseCode: "AZ-104",
    courseTitle: "Scott Duffy AZ-104",
    title: "Scott Duffy AZ-104: Section 22 & 23",
    hours: 2.0,
    udemyRef: "Scott Duffy AZ-104 (Section 22: VM Scale Sets & Sec 23: Standard Load Balancer)",
    topic: "VMSS autoscale rules, Standard Load Balancer, Health Probes, Backend Pools.",
    outcome: "Configure Layer 4 traffic distribution and autoscaling.",
    lab: "Provision Internal Load Balancer with health probe.",
    revision: "Public vs Internal Load Balancers.",
    category: "Networking"
  },
  {
    day: 13,
    week: 2,
    courseId: 1,
    courseCode: "AZ-104",
    courseTitle: "Scott Duffy AZ-104",
    title: "Scott Duffy AZ-104: Section 24",
    hours: 2.0,
    udemyRef: "Scott Duffy AZ-104 (Section 24: Application Gateway & Layer 7 Load Balancing)",
    topic: "Application Gateway, URL-based routing, SSL termination.",
    outcome: "Configure Layer 7 web traffic distribution.",
    lab: "Deploy App Gateway with path-based routing rule.",
    revision: "AppGW listener configurations.",
    category: "Networking"
  },
  {
    day: 14,
    week: 2,
    courseId: 1,
    courseCode: "AZ-104",
    courseTitle: "Scott Duffy AZ-104",
    title: "Scott Duffy AZ-104: Section 25",
    hours: 1.5,
    udemyRef: "Scott Duffy AZ-104 (Section 25: Azure Monitor, Diagnostic Settings & Alerts)",
    topic: "Log Analytics Workspace, Diagnostic Settings, Metrics, Alerts.",
    outcome: "Configure central logging infrastructure.",
    lab: "Deploy Log Analytics Workspace and enable Diagnostic Settings.",
    revision: "Log retention tiers.",
    category: "Monitoring"
  },
  {
    day: 15,
    week: 2,
    courseId: 1,
    courseCode: "AZ-104",
    courseTitle: "Scott Duffy AZ-104",
    title: "Scott Duffy AZ-104: Section 26 & Project 1 Deployment",
    hours: 2.5,
    udemyRef: "Scott Duffy AZ-104 (Section 26: Practice Exam, Course Review & Project 1)",
    topic: "Enterprise Hub-and-Spoke Perimeter Architecture.",
    outcome: "Complete automated deployment of Project 1.",
    lab: "Deploy `azure-hub-spoke-perimeter` Terraform code and run validation script.",
    revision: "Review AZ-104 summary checklist.",
    category: "Project"
  },

  // =========================================================================
  // COURSE 2: ALAN RODRIGUES - AZ-500 (REALISTIC SECTION TIMINGS)
  // =========================================================================
  {
    day: 16,
    week: 3,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Alan Rodrigues AZ-500: Section 1 & Section 2",
    hours: 1.5,
    udemyRef: "Alan Rodrigues AZ-500 (Section 1: Intro & Section 2: Entra ID App Registrations)",
    topic: "App Registrations, Service Principals, OAuth2/OIDC, Delegated vs App permissions.",
    outcome: "Secure workload authentication for enterprise applications.",
    lab: "Register App Registration with certificate credentials.",
    revision: "Admin consent workflows.",
    category: "IAM"
  },
  {
    day: 17,
    week: 3,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Alan Rodrigues AZ-500: Section 3",
    hours: 2.0,
    udemyRef: "Alan Rodrigues AZ-500 (Section 3: Conditional Access, MFA & Passkeys)",
    topic: "CA Signals, Decisions, FIDO2/Passkeys, Session Controls.",
    outcome: "Enforce zero-trust authentication policies.",
    lab: "Create CA policy enforcing phishing-resistant MFA for admins.",
    revision: "Report-Only mode analysis.",
    category: "IAM"
  },
  {
    day: 18,
    week: 3,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Alan Rodrigues AZ-500: Section 4",
    hours: 1.5,
    udemyRef: "Alan Rodrigues AZ-500 (Section 4: Entra Privileged Identity Management)",
    topic: "Just-In-Time (JIT) elevation, approval workflows, Access Reviews.",
    outcome: "Eliminate standing administrative privileges.",
    lab: "Configure PIM for Contributor role requiring MFA & approval.",
    revision: "PIM activation audit logs.",
    category: "IAM"
  },
  {
    day: 19,
    week: 3,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Alan Rodrigues AZ-500: Section 5",
    hours: 1.5,
    udemyRef: "Alan Rodrigues AZ-500 (Section 5: Managed Identities & Workload Identities)",
    topic: "System-Assigned vs User-Assigned Managed Identities, IMDS endpoint, OIDC Federation.",
    outcome: "Eliminate hardcoded secrets in source code.",
    lab: "Fetch OAuth token via IMDS cURL and query Key Vault API.",
    revision: "IMDS token renewal.",
    category: "IAM"
  },
  {
    day: 20,
    week: 3,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Project 3 Deployment: Entra ID Governance Engine",
    hours: 2.5,
    udemyRef: "Alan Rodrigues AZ-500 (Section 5: IAM Security Lab)",
    topic: "Automated Entra ID Governance Engine.",
    outcome: "Complete automated deployment of Project 3.",
    lab: "Deploy `entra-iam-governance-as-code` script.",
    revision: "Review Entra ID IAM domain.",
    category: "Project"
  },
  {
    day: 21,
    week: 4,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Alan Rodrigues AZ-500: Section 6",
    hours: 2.5,
    udemyRef: "Alan Rodrigues AZ-500 (Section 6: Azure Firewall Premium & TLS Inspection)",
    topic: "IDPS, TLS Inspection, FQDN filtering, Network Rules.",
    outcome: "Configure central firewall with deep packet inspection.",
    lab: "Configure Azure Firewall policy with TLS decryption cert.",
    revision: "SNI filtering vs TLS inspection.",
    category: "Perimeter"
  },
  {
    day: 22,
    week: 4,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Alan Rodrigues AZ-500: Section 7",
    hours: 2.0,
    udemyRef: "Alan Rodrigues AZ-500 (Section 7: Application Gateway WAF v2)",
    topic: "OWASP 3.2 ruleset, Prevention Mode, Custom Rules.",
    outcome: "Protect public web applications against Layer 7 attacks.",
    lab: "Deploy AppGW WAF v2 and test SQLi 403 block.",
    revision: "WAF exclusion lists.",
    category: "Perimeter"
  },
  {
    day: 23,
    week: 4,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Alan Rodrigues AZ-500: Section 8",
    hours: 1.5,
    udemyRef: "Alan Rodrigues AZ-500 (Section 8: Network Isolation & UDR Routing)",
    topic: "NSGs, ASGs, UDR Next Hop VirtualAppliance, Forced Tunneling.",
    outcome: "Enforce microsegmentation and egress isolation.",
    lab: "Configure UDR 0.0.0.0/0 route table to Azure Firewall.",
    revision: "NSG evaluation precedence.",
    category: "Networking"
  },
  {
    day: 24,
    week: 4,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Alan Rodrigues AZ-500: Section 9",
    hours: 2.0,
    udemyRef: "Alan Rodrigues AZ-500 (Section 9: Private Endpoints & Private Link)",
    topic: "Private Endpoints, Private DNS Zones, Split-horizon DNS.",
    outcome: "Eliminate public IPs on Azure PaaS services.",
    lab: "Deploy Storage Private Endpoint with Private DNS Zone.",
    revision: "Private Link DNS resolution.",
    category: "Data Security"
  },
  {
    day: 25,
    week: 4,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Alan Rodrigues AZ-500: Section 10",
    hours: 1.5,
    udemyRef: "Alan Rodrigues AZ-500 (Section 10: Azure Storage Security)",
    topic: "Disable Shared Key access, Stored Access Policies, Entra ID Auth.",
    outcome: "Prevent unauthenticated Blob exfiltration.",
    lab: "Disable Shared Key access (`--allow-shared-key-access false`).",
    revision: "SAS delegation keys.",
    category: "Data Security"
  },
  {
    day: 26,
    week: 4,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Alan Rodrigues AZ-500: Section 11",
    hours: 1.5,
    udemyRef: "Alan Rodrigues AZ-500 (Section 11: Azure Key Vault Architecture)",
    topic: "Soft-delete, Purge Protection, Azure RBAC mode, Managed HSM.",
    outcome: "Securely manage enterprise secrets and keys.",
    lab: "Deploy Key Vault in Azure RBAC mode and test secrets access.",
    revision: "Key Vault diagnostic logs.",
    category: "Key Management"
  },
  {
    day: 27,
    week: 4,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Alan Rodrigues AZ-500: Section 12 & Section 13",
    hours: 2.0,
    udemyRef: "Alan Rodrigues AZ-500 (Section 12: Disk Encryption & Section 13: Database Security)",
    topic: "ADE, SSE, Customer-Managed Keys (CMK), SQL Dynamic Data Masking, Always Encrypted.",
    outcome: "Implement end-to-end data encryption at rest.",
    lab: "Encrypt VM OS disk using Key Vault RSA 4096-bit key.",
    revision: "KEK vs DEK envelope pattern.",
    category: "Data Security"
  },
  {
    day: 28,
    week: 4,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Project 2 Deployment: Zero-Trust Private Data Lake",
    hours: 2.5,
    udemyRef: "Alan Rodrigues AZ-500 (Section 13: Data Security Lab)",
    topic: "Zero-Trust Private Data Lake with Private Link.",
    outcome: "Complete automated deployment of Project 2.",
    lab: "Deploy `azure-private-datalake-security` Terraform code.",
    revision: "Review Azure Data & Key Vault domain.",
    category: "Project"
  },
  {
    day: 29,
    week: 5,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Alan Rodrigues AZ-500: Section 16",
    hours: 1.5,
    udemyRef: "Alan Rodrigues AZ-500 (Section 16: Microsoft Sentinel Log Ingestion)",
    topic: "Log Analytics Workspace, Data Connectors, Analytics vs Basic table tiers.",
    outcome: "Architect enterprise SIEM log ingestion.",
    lab: "Deploy Sentinel on LAW and enable Entra ID connectors.",
    revision: "Ingestion cost control.",
    category: "SIEM"
  },
  {
    day: 30,
    week: 5,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Alan Rodrigues AZ-500: Section 17",
    hours: 2.5,
    udemyRef: "Alan Rodrigues AZ-500 (Section 17: Master KQL Syntax & Log Queries)",
    topic: "where, project, extend, summarize, render, join, lookup.",
    outcome: "Write high-performance KQL log queries.",
    lab: "Query SigninLogs for failed logins grouped by User and IP.",
    revision: "Query optimization using `has`.",
    category: "KQL"
  },
  {
    day: 31,
    week: 5,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Alan Rodrigues AZ-500: Section 17 (Advanced KQL)",
    hours: 2.5,
    udemyRef: "Alan Rodrigues AZ-500 (Section 17: Time Series & Anomaly Queries)",
    topic: "make-series, series_decompose_anomalies, binning.",
    outcome: "Build statistical anomaly detection queries.",
    lab: "Run time-series baseline query on Azure Activity deletion events.",
    revision: "Time binning functions.",
    category: "KQL"
  },
  {
    day: 32,
    week: 5,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Alan Rodrigues AZ-500: Section 18",
    hours: 1.5,
    udemyRef: "Alan Rodrigues AZ-500 (Section 18: Data Collection Rules & AMA)",
    topic: "Azure Monitor Agent (AMA), DCR KQL transformations.",
    outcome: "Filter noise at ingestion to drop costs by 40%.",
    lab: "Configure DCR dropping Event ID 4688 noise.",
    revision: "DCR association to Arc servers.",
    category: "SIEM"
  },
  {
    day: 33,
    week: 5,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Alan Rodrigues AZ-500: Section 19",
    hours: 1.5,
    udemyRef: "Alan Rodrigues AZ-500 (Section 19: Sentinel Analytic Rules & Triage)",
    topic: "Scheduled vs NRT rules, Entity Mapping (Account, Host, IP).",
    outcome: "Construct high-fidelity threat detection rules.",
    lab: "Write custom KQL Analytic Rule for brute-force logins.",
    revision: "Incident creation thresholds.",
    category: "Detection"
  },
  {
    day: 34,
    week: 5,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Alan Rodrigues AZ-500: Section 20",
    hours: 2.0,
    udemyRef: "Alan Rodrigues AZ-500 (Section 20: Sentinel Automation & Logic Apps SOAR)",
    topic: "Automation rules, Logic Apps playbooks, PIM revocation.",
    outcome: "Automate incident response actions.",
    lab: "Create Logic App playbook disabling compromised Entra ID user.",
    revision: "Managed identity auth for playbooks.",
    category: "SOAR"
  },
  {
    day: 35,
    week: 5,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Project 5 Deployment: Sentinel SIEM & SOAR Engine",
    hours: 2.5,
    udemyRef: "Alan Rodrigues AZ-500 (Section 20: Sentinel SOAR Lab)",
    topic: "Microsoft Sentinel Enterprise SIEM Engine.",
    outcome: "Complete automated deployment of Project 5.",
    lab: "Deploy `sentinel-kql-soar-engine` with 20 custom KQL rules.",
    revision: "Review KQL & Sentinel architecture.",
    category: "Project"
  },
  {
    day: 36,
    week: 6,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Alan Rodrigues AZ-500: Section 14",
    hours: 1.5,
    udemyRef: "Alan Rodrigues AZ-500 (Section 14: Defender for Cloud & Secure Score)",
    topic: "CSPM vs CWPP, Attack Path Analysis, Cloud Security Explorer.",
    outcome: "Prioritize cloud security posture risks.",
    lab: "Enable MDC Defender plans and fix non-compliant findings.",
    revision: "Secure score calculation.",
    category: "Governance"
  },
  {
    day: 37,
    week: 6,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Alan Rodrigues AZ-500: Section 15",
    hours: 1.5,
    udemyRef: "Alan Rodrigues AZ-500 (Section 15: Defender for Servers & Containers)",
    topic: "Qualys vulnerability scanning, Agentless eBPF container scanning.",
    outcome: "Secure compute workloads and ACR registries.",
    lab: "Push container image to ACR and inspect vulnerability report.",
    revision: "eBPF technology in Defender.",
    category: "Containers"
  },
  {
    day: 60,
    week: 8,
    courseId: 2,
    courseCode: "AZ-500",
    courseTitle: "Alan Rodrigues AZ-500",
    title: "Alan Rodrigues AZ-500: Section 21 & Certification Exam Milestone",
    hours: 3.0,
    udemyRef: "Alan Rodrigues AZ-500 (Section 21: Practice Tests & Final Review)",
    topic: "AZ-500 Azure Security Engineer Associate Exam.",
    outcome: "Pass AZ-500 Exam (>700 Score). Receive Azure Security Engineer Badge.",
    lab: "Complete 2 AZ-500 practice exams.",
    revision: "Final review of Entra ID, Key Vault, Firewall, and Sentinel.",
    category: "Certification"
  },

  // =========================================================================
  // COURSE 3: ALAN RODRIGUES - SC-100 (REALISTIC SECTION TIMINGS)
  // =========================================================================
  {
    day: 61,
    week: 9,
    courseId: 3,
    courseCode: "SC-100",
    courseTitle: "Alan Rodrigues SC-100",
    title: "Alan Rodrigues SC-100: Section 1 & Section 2",
    hours: 2.0,
    udemyRef: "Alan Rodrigues SC-100 (Section 1: Architecture Overview & Section 2: Zero Trust Strategy)",
    topic: "Explicit Verification, Least Privilege Access, Assume Breach principles.",
    outcome: "Architect zero-trust enterprise perimeters.",
    lab: "Model zero-trust architecture diagram for multi-tenant SaaS.",
    revision: "NIST 800-207 pillars.",
    category: "Architecture"
  },
  {
    day: 62,
    week: 9,
    courseId: 3,
    courseCode: "SC-100",
    courseTitle: "Alan Rodrigues SC-100",
    title: "Alan Rodrigues SC-100: Section 3",
    hours: 2.0,
    udemyRef: "Alan Rodrigues SC-100 (Section 3: Enterprise Landing Zones)",
    topic: "Management Group Hierarchy, Platform vs Workloads, Subscription Vending.",
    outcome: "Design multi-subscription enterprise governance.",
    lab: "Deploy ALZ Management Group structure via Terraform.",
    revision: "Policy assignment scopes.",
    category: "Architecture"
  },
  {
    day: 63,
    week: 9,
    courseId: 3,
    courseCode: "SC-100",
    courseTitle: "Alan Rodrigues SC-100",
    title: "Alan Rodrigues SC-100: Section 4",
    hours: 1.5,
    udemyRef: "Alan Rodrigues SC-100 (Section 4: Policy Guardrails & Compliance)",
    topic: "Policy Definitions, Initiatives, Effects (Audit, Deny, DeployIfNotExists).",
    outcome: "Enforce continuous compliance policy guardrails.",
    lab: "Write custom Azure Policy denying public IP creation on VMs.",
    revision: "Policy evaluation cycles.",
    category: "Governance"
  },
  {
    day: 64,
    week: 9,
    courseId: 3,
    courseCode: "SC-100",
    courseTitle: "Alan Rodrigues SC-100",
    title: "Project 4 Deployment: ALZ Policy Guardrails Pipeline",
    hours: 2.5,
    udemyRef: "Alan Rodrigues SC-100 (Section 4: Policy Guardrails Lab)",
    topic: "Azure Enterprise Landing Zone Guardrails.",
    outcome: "Complete automated deployment of Project 4.",
    lab: "Deploy `azure-landing-zone-policy-pipeline` Terraform code.",
    revision: "Review ALZ Architecture.",
    category: "Project"
  },
  {
    day: 65,
    week: 10,
    courseId: 3,
    courseCode: "SC-100",
    courseTitle: "Alan Rodrigues SC-100",
    title: "Alan Rodrigues SC-100: Section 5",
    hours: 1.5,
    udemyRef: "Alan Rodrigues SC-100 (Section 5: Data Security & Ransomware Protection)",
    topic: "WORM Storage immutability policies, Air-gapped backups, Soft-delete.",
    outcome: "Protect enterprise data against ransomware destruction.",
    lab: "Configure Storage Immutability Policy in Locked state.",
    revision: "WORM storage compliance.",
    category: "Data Security"
  },
  {
    day: 66,
    week: 10,
    courseId: 3,
    courseCode: "SC-100",
    courseTitle: "Alan Rodrigues SC-100",
    title: "Alan Rodrigues SC-100: Section 6",
    hours: 2.0,
    udemyRef: "Alan Rodrigues SC-100 (Section 6: Incident Response & Auto-Isolation)",
    topic: "Automated Host Isolation, Forensic Snapshots, Volatile Memory Capture.",
    outcome: "Build event-driven incident containment workflows.",
    lab: "Deploy `azure-automated-forensics-ir` auto-isolation function.",
    revision: "Digital forensics chain of custody.",
    category: "Incident Response"
  },
  {
    day: 67,
    week: 10,
    courseId: 3,
    courseCode: "SC-100",
    courseTitle: "Alan Rodrigues SC-100",
    title: "Alan Rodrigues SC-100: Section 7 & Project 6 Deployment",
    hours: 2.5,
    udemyRef: "Alan Rodrigues SC-100 (Section 7: Multi-Cloud & Hybrid Security Architecture)",
    topic: "Automated Cloud Forensics & Host Isolation in Azure.",
    outcome: "Complete automated deployment of Project 6.",
    lab: "Deploy `azure-automated-forensics-ir` pipeline.",
    revision: "Review Incident Response playbooks.",
    category: "Project"
  },

  // =========================================================================
  // COURSE 4: STEPHANE MAAREK - AWS SECURITY (REALISTIC TIMINGS)
  // =========================================================================
  {
    day: 81,
    week: 11,
    courseId: 4,
    courseCode: "AWS-SEC",
    courseTitle: "Stephane Maarek AWS Sec",
    title: "Stephane Maarek AWS Security: Section 1 & Section 2",
    hours: 2.0,
    udemyRef: "Stephane Maarek AWS Security (Section 1: IAM Policies & Section 2: STS AssumeRole)",
    topic: "AssumeRole API, Trust Policies, ExternalId validation, SCPs.",
    outcome: "Eliminate static long-lived AWS access keys.",
    lab: "Deploy cross-account IAM role with ExternalId validation.",
    revision: "Confused deputy problem.",
    category: "AWS IAM"
  },
  {
    day: 82,
    week: 12,
    courseId: 4,
    courseCode: "AWS-SEC",
    courseTitle: "Stephane Maarek AWS Sec",
    title: "Project 7 Deployment: AWS Cross-Account IAM Engine",
    hours: 2.5,
    udemyRef: "Stephane Maarek AWS Security (Section 2: IAM Lab)",
    topic: "AWS Cross-Account Security & IAM Governance Engine.",
    outcome: "Complete automated deployment of Project 7.",
    lab: "Deploy `aws-cross-account-iam-framework` Terraform code.",
    revision: "Review AWS IAM policy evaluation.",
    category: "Project"
  },
  {
    day: 83,
    week: 12,
    courseId: 4,
    courseCode: "AWS-SEC",
    courseTitle: "Stephane Maarek AWS Sec",
    title: "Stephane Maarek AWS Security: Section 3 & Section 4",
    hours: 2.0,
    udemyRef: "Stephane Maarek AWS Security (Section 3: VPC Endpoints & Section 4: KMS Key Policies)",
    topic: "Interface & Gateway Endpoints, Endpoint Policies, KMS CMK Key Policies.",
    outcome: "Isolate AWS API traffic inside private VPC.",
    lab: "Deploy Gateway VPC Endpoint for S3 with restrictive Endpoint Policy.",
    revision: "KMS Key Policy evaluation.",
    category: "AWS Security"
  },
  {
    day: 84,
    week: 12,
    courseId: 4,
    courseCode: "AWS-SEC",
    courseTitle: "Stephane Maarek AWS Sec",
    title: "Project 8 Deployment: AWS VPC Endpoint Security",
    hours: 2.5,
    udemyRef: "Stephane Maarek AWS Security (Section 3: VPC Lab)",
    topic: "AWS VPC Endpoint Security & Egress Filtering.",
    outcome: "Complete automated deployment of Project 8.",
    lab: "Deploy `aws-vpc-endpoint-security` Terraform module.",
    revision: "Review AWS VPC networking.",
    category: "Project"
  },
  {
    day: 85,
    week: 12,
    courseId: 4,
    courseCode: "AWS-SEC",
    courseTitle: "Stephane Maarek AWS Sec",
    title: "Stephane Maarek AWS Security: Section 5, 6, 7 & 8",
    hours: 2.0,
    udemyRef: "Stephane Maarek AWS Security (Section 5: GuardDuty, Sec 6: Security Hub, Sec 7: CloudTrail, Sec 8: SSM)",
    topic: "GuardDuty ML threat engine, Security Hub CIS benchmarks, CloudTrail audit, SSM Session Manager.",
    outcome: "Enable automated AWS threat detection.",
    lab: "Enable GuardDuty and Security Hub across accounts.",
    revision: "CloudTrail log digest validation.",
    category: "AWS Threat Detection"
  },

  // =========================================================================
  // COURSE 5: ZEAL VORA - TERRAFORM ASSOCIATE (REALISTIC TIMINGS)
  // =========================================================================
  {
    day: 96,
    week: 13,
    courseId: 5,
    courseCode: "TERRAFORM",
    courseTitle: "Zeal Vora Terraform",
    title: "Zeal Vora Terraform: Section 1, 2 & 3",
    hours: 2.0,
    udemyRef: "Zeal Vora Terraform (Section 1: Fundamentals, Sec 2: State Locking, Sec 3: Modules)",
    topic: "Terraform state encryption, Remote State Locking (Azure Blob / S3), Reusable Modules.",
    outcome: "Write secure enterprise Terraform code.",
    lab: "Configure Terraform remote backend with state locking.",
    revision: "State file security risks.",
    category: "DevSecOps"
  },
  {
    day: 97,
    week: 13,
    courseId: 5,
    courseCode: "TERRAFORM",
    courseTitle: "Zeal Vora Terraform",
    title: "Zeal Vora Terraform: Section 4, 5 & 6",
    hours: 2.0,
    udemyRef: "Zeal Vora Terraform (Section 4: Checkov/Tfsec, Sec 5: GitHub Actions, Sec 6: Dynamic Secret Rotation)",
    topic: "Checkov, Tfsec, Gitleaks, Semgrep integration in CI/CD pipelines.",
    outcome: "Block insecure IaC configurations automatically.",
    lab: "Run Checkov audit against Terraform directory in GitHub Actions.",
    revision: "Checkov rule severity scoring.",
    category: "DevSecOps"
  },
  {
    day: 98,
    week: 13,
    courseId: 5,
    courseCode: "TERRAFORM",
    courseTitle: "Zeal Vora Terraform",
    title: "Project 9 Deployment: DevSecOps CI/CD Guardrails Engine",
    hours: 2.5,
    udemyRef: "Zeal Vora Terraform (Section 5: CI/CD Security Lab)",
    topic: "DevSecOps CI/CD Pipeline Guardrails Engine.",
    outcome: "Complete automated deployment of Project 9.",
    lab: "Deploy `devsecops-pipeline-guardrails` GitHub workflow.",
    revision: "Review DevSecOps pipeline metrics.",
    category: "Project"
  },

  // =========================================================================
  // COURSE 6: MUMSHAD MANNAMBETH - CKS (REALISTIC TIMINGS)
  // =========================================================================
  {
    day: 106,
    week: 14,
    courseId: 6,
    courseCode: "CKS",
    courseTitle: "Mumshad CKS K8s Sec",
    title: "Mumshad CKS K8s Sec: Section 1 & Section 2",
    hours: 2.0,
    udemyRef: "Mumshad CKS (Section 1: Distroless Containers & Section 2: Pod Security Admission)",
    topic: "Distroless base images, Non-root USER 10001, Pod Security Admission restricted profile.",
    outcome: "Build minimal hardened container images.",
    lab: "Write multistage distroless Dockerfile for Go/Node app.",
    revision: "Container breakout attack vectors.",
    category: "Containers"
  },
  {
    day: 107,
    week: 14,
    courseId: 6,
    courseCode: "CKS",
    courseTitle: "Mumshad CKS K8s Sec",
    title: "Mumshad CKS K8s Sec: Section 3 & Section 4",
    hours: 2.0,
    udemyRef: "Mumshad CKS (Section 3: NetworkPolicies & Section 4: Falco Runtime Threat Detection)",
    topic: "Default-deny NetworkPolicies, Falco eBPF threat rules.",
    outcome: "Enforce zero-trust pod isolation in K8s.",
    lab: "Apply default-deny-all NetworkPolicy to namespace.",
    revision: "PSA enforcement modes.",
    category: "Containers"
  },
  {
    day: 108,
    week: 14,
    courseId: 6,
    courseCode: "CKS",
    courseTitle: "Mumshad CKS K8s Sec",
    title: "Mumshad CKS K8s Sec: Section 5 & Section 6",
    hours: 2.0,
    udemyRef: "Mumshad CKS (Section 5: Trivy & Sigstore Cosign Signing & Section 6: Architecture Audit)",
    topic: "Trivy image scanning, Sigstore Cosign signing, cluster audit logging.",
    outcome: "Detect runtime container anomalies and secure container supply chain.",
    lab: "Deploy Falco sensor and trigger simulated shell exec alert.",
    revision: "Falco rule syntax.",
    category: "Containers"
  },
  {
    day: 109,
    week: 14,
    courseId: 6,
    courseCode: "CKS",
    courseTitle: "Mumshad CKS K8s Sec",
    title: "Project 10 Deployment: K8s Zero-Trust Runtime Engine",
    hours: 2.5,
    udemyRef: "Mumshad CKS (Section 6: K8s Security Lab)",
    topic: "Kubernetes Zero-Trust & Falco Runtime Security.",
    outcome: "Complete automated deployment of Project 10.",
    lab: "Deploy `k8s-zero-trust-runtime-security` Helm manifests.",
    revision: "Review K8s security controls.",
    category: "Project"
  },
  {
    day: 120,
    week: 16,
    courseId: 6,
    courseCode: "CKS",
    courseTitle: "Mumshad CKS K8s Sec",
    title: "Alan Rodrigues SC-100: Section 8 & SC-100 Final Exam Milestone",
    hours: 3.0,
    udemyRef: "Alan Rodrigues SC-100 (Section 8: Practice Test & Final Architecture Review)",
    topic: "SC-100 Cybersecurity Architect Expert Exam & 15 Repos Audit.",
    outcome: "Pass SC-100 Exam (>700 Score). 100% Readiness achieved. Begin recruiter outreach.",
    lab: "Execute final pre-flight verification checklist.",
    revision: "Master Review of all 700 Q&A Cards.",
    category: "Certification"
  }
];

export const PROJECTS_LIST = [
  {
    id: 1,
    title: "Azure Enterprise Hub-and-Spoke Secure Network Perimeter",
    repo: "azure-hub-spoke-perimeter",
    category: "Azure Networking",
    difficulty: "Advanced",
    alignedCourse: "Course 1: Scott Duffy AZ-104 (Section 14 & 26)",
    tools: ["Terraform", "Azure Firewall Premium", "App Gateway WAF v2", "Azure Bastion", "UDR"],
    description: "Architected and deployed an automated Azure Hub-and-Spoke network perimeter via Terraform across 3 regions, terminating WAF inbound traffic and filtering outbound egress via Azure Firewall Premium.",
    resumeBullet: "Architected and deployed an automated Azure Hub-and-Spoke network perimeter via Terraform across 3 regions, integrating Azure Firewall Premium TLS inspection and WAF v2, eliminating 100% of workload public IP exposure."
  },
  {
    id: 2,
    title: "Azure Zero-Trust Private Data Lake with Private Link",
    repo: "azure-private-datalake-security",
    category: "Data Security",
    difficulty: "Advanced",
    alignedCourse: "Course 2: Alan Rodrigues AZ-500 (Section 9 & 13)",
    tools: ["Private Link", "Private DNS Zones", "Storage Accounts", "Azure SQL", "Managed Identity"],
    description: "Enterprise data lake isolated completely from the internet using Azure Private Endpoints, disabling SAS token auth and enforcing Entra ID User-Assigned Managed Identity authentication.",
    resumeBullet: "Engineered zero-trust storage and database architecture utilizing Azure Private Endpoints and User-Assigned Managed Identities, disabling SAS Key authentication and securing 50TB+ analytical workloads."
  },
  {
    id: 3,
    title: "Automated Entra ID Governance Engine (PIM & CA as Code)",
    repo: "entra-iam-governance-as-code",
    category: "Identity & Access",
    difficulty: "Intermediate",
    alignedCourse: "Course 2: Alan Rodrigues AZ-500 (Section 3, 4 & 5)",
    tools: ["Entra ID", "Conditional Access", "PIM", "Workload Identity Federation", "GitHub Actions"],
    description: "Policy-as-Code definitions for Entra ID enforcing phishing-resistant Conditional Access, PIM JIT elevation workflows, and OIDC Workload Identity Federation for GitHub Actions.",
    resumeBullet: "Implemented Entra ID governance-as-code deploying 14 Zero-Trust Conditional Access policies and PIM JIT elevation workflows, reducing standing administrative privileges by 85%."
  },
  {
    id: 4,
    title: "Azure Enterprise Landing Zone (ALZ) Policy Guardrails",
    repo: "azure-landing-zone-policy-pipeline",
    category: "Governance",
    difficulty: "Advanced",
    alignedCourse: "Course 3: Alan Rodrigues SC-100 (Section 3 & 4)",
    tools: ["Azure Management Groups", "Azure Policy", "Bicep", "GitHub Actions"],
    description: "Multi-subscription management group topology with custom Azure Policy definitions enforced via automated GitHub Actions CI/CD pipelines.",
    resumeBullet: "Designed enterprise Azure Landing Zone archetype policy framework enforcing automatic TLS 1.2+, mandatory encryption at rest, maintaining continuous compliance score of 98%+."
  },
  {
    id: 5,
    title: "Microsoft Sentinel Enterprise SIEM Engine & SOAR",
    repo: "sentinel-kql-soar-engine",
    category: "SIEM & SOAR",
    difficulty: "Advanced",
    alignedCourse: "Course 2: Alan Rodrigues AZ-500 (Section 16, 17, 18, 19 & 20)",
    tools: ["Microsoft Sentinel", "KQL", "Logic Apps", "ARM", "REST APIs"],
    description: "Microsoft Sentinel instance ingesting multicloud logs with 35+ custom KQL detection rules mapped to MITRE ATT&CK, coupled with Logic App automated mitigation playbooks.",
    resumeBullet: "Developed 35+ custom KQL detection rules mapped to MITRE ATT&CK in Microsoft Sentinel, coupled with Logic App SOAR playbooks that reduced MTTR from 4 hours to under 2 minutes."
  },
  {
    id: 6,
    title: "Automated Cloud Forensics & Host Isolation in Azure",
    repo: "azure-automated-forensics-ir",
    category: "Incident Response",
    difficulty: "Advanced",
    alignedCourse: "Course 3: Alan Rodrigues SC-100 (Section 6 & 7)",
    tools: ["Azure Functions", "Event Grid", "Az CLI", "Defender for Cloud"],
    description: "Serverless IR workflow triggered by Defender alerts that automatically isolates compromised VMs from the network and captures forensic OS disk snapshots within 30 seconds.",
    resumeBullet: "Created an event-driven auto-isolation pipeline using Azure Functions and Event Grid, automating memory capture and network quarantine for compromised IaaS instances within 30 seconds."
  },
  {
    id: 7,
    title: "AWS Cross-Account Security & IAM Governance Engine",
    repo: "aws-cross-account-iam-framework",
    category: "AWS IAM",
    difficulty: "Intermediate",
    alignedCourse: "Course 4: Stephane Maarek AWS Sec (Section 1 & 2)",
    tools: ["AWS IAM", "AWS Organizations", "AWS STS", "Terraform"],
    description: "Multi-account AWS security architecture using AWS Organizations, SCPs, and STS cross-account assume-role pipelines with External ID validation.",
    resumeBullet: "Architected multi-account IAM role delegation model using AWS STS and SCPs, enforcing strict permission boundaries and eliminating long-lived static AWS access keys."
  },
  {
    id: 8,
    title: "AWS VPC Endpoint Security & Egress Filtering",
    repo: "aws-vpc-endpoint-security",
    category: "AWS Security",
    difficulty: "Advanced",
    alignedCourse: "Course 4: Stephane Maarek AWS Sec (Section 3)",
    tools: ["AWS VPC", "VPC Endpoints", "AWS Network Firewall", "Terraform"],
    description: "Secure AWS network perimeter using Private Subnets, Gateway & Interface Endpoints, Endpoint Policies, and AWS Network Firewall FQDN filtering.",
    resumeBullet: "Designed secure AWS egress network filtering using AWS Network Firewall and Gateway Endpoints, restricting outbound traffic to approved FQDNs and reducing NAT egress charges."
  },
  {
    id: 9,
    title: "DevSecOps CI/CD Pipeline Guardrails Engine",
    repo: "devsecops-pipeline-guardrails",
    category: "DevSecOps",
    difficulty: "Intermediate",
    alignedCourse: "Course 5: Zeal Vora Terraform (Section 4 & 5)",
    tools: ["GitHub Actions", "Gitleaks", "Semgrep", "Checkov", "Trivy"],
    description: "Enterprise GitHub Actions workflow integrating Gitleaks secret scanning, Semgrep SAST, Checkov IaC checks, and Trivy container scanning, blocking non-compliant PRs.",
    resumeBullet: "Architected end-to-end DevSecOps CI/CD security pipeline enforcing static analysis, secret scanning, and IaC vulnerability checks, preventing 200+ security defects annually."
  },
  {
    id: 10,
    title: "Kubernetes (AKS/EKS) Zero-Trust & Falco Runtime",
    repo: "k8s-zero-trust-runtime-security",
    category: "Containers",
    difficulty: "Advanced",
    alignedCourse: "Course 6: Mumshad Mannambeth CKS (Section 2, 3 & 4)",
    tools: ["Kubernetes", "AKS", "Calico NetworkPolicy", "Falco", "Trivy"],
    description: "Hardened Kubernetes cluster configured with Pod Security Admission restricted profile, Calico NetworkPolicies, and Falco runtime threat detection.",
    resumeBullet: "Hardened enterprise AKS cluster using Kubernetes NetworkPolicies, Pod Security Standards, and Falco runtime detection, capturing real-time pod anomaly executions."
  },
  {
    id: 11,
    title: "Multi-Cloud Dynamic Secret Rotation Pipeline",
    repo: "multicloud-automated-secret-rotation",
    category: "Key Management",
    difficulty: "Intermediate",
    alignedCourse: "Course 5: Zeal Vora Terraform (Section 6)",
    tools: ["Azure Key Vault", "AWS Secrets Manager", "Python", "Serverless"],
    description: "Automated secret rotation framework utilizing Azure Key Vault and AWS Secrets Manager with serverless functions for 30-day database password updates without downtime.",
    resumeBullet: "Engineered dynamic automated database secret rotation pipelines across Azure and AWS using serverless functions, guaranteeing 30-day credential rotation cycles."
  },
  {
    id: 12,
    title: "Multi-Cloud CSPM Compliance Engine",
    repo: "multicloud-cspm-compliance-engine",
    category: "Governance",
    difficulty: "Intermediate",
    alignedCourse: "Course 3: Alan Rodrigues SC-100 (Section 4 & 7)",
    tools: ["Azure Policy", "AWS Security Hub", "Security Lake", "Python"],
    description: "Aggregated multi-cloud compliance findings against CIS Benchmarks and NIST SP 800-53 using Azure Policy Initiatives and AWS Security Hub.",
    resumeBullet: "Unified multi-cloud compliance reporting across Azure and AWS against CIS Benchmarks, creating real-time posture visibility dashboards for executive leadership."
  },
  {
    id: 13,
    title: "Container Supply Chain Security & Sigstore Cosign",
    repo: "container-supply-chain-security",
    category: "DevSecOps",
    difficulty: "Advanced",
    alignedCourse: "Course 6: Mumshad Mannambeth CKS (Section 5)",
    tools: ["Cosign", "Trivy", "Azure Container Registry", "GitHub Actions"],
    description: "Container supply chain security scanning images via Trivy and cryptographically signing verified images with Cosign before pushing to registry.",
    resumeBullet: "Implemented container supply chain cryptographic signing pipeline using Sigstore Cosign and ACR, blocking untrusted container images from executing in production AKS."
  },
  {
    id: 14,
    title: "Serverless API Security Architecture & OAuth2",
    repo: "serverless-api-security-architecture",
    category: "API Security",
    difficulty: "Intermediate",
    alignedCourse: "Course 2: Alan Rodrigues AZ-500 (Section 7 & 13)",
    tools: ["Azure APIM", "Azure Functions", "App Gateway WAF", "Entra ID"],
    description: "High-scale serverless API architecture protected by API Management (APIM), WAF rate limiting, and Entra ID JWT authorization.",
    resumeBullet: "Designed secure serverless API Gateway architecture enforcing OAuth2 JWT validation, WAF layer 7 attack mitigation, and IP rate-limiting."
  },
  {
    id: 15,
    title: "Terraform Automated Cloud Attack Range",
    repo: "terraform-cloud-security-attack-range",
    category: "Detection",
    difficulty: "Advanced",
    alignedCourse: "Course 5: Zeal Vora Terraform (Section 1 to 6)",
    tools: ["Terraform", "Python", "Microsoft Sentinel", "AWS GuardDuty"],
    description: "Repeatable Terraform target range deploying intentional security misconfigurations, running automated attack scripts, and validating detection rule alerts.",
    resumeBullet: "Developed an automated cloud attack range in Terraform to validate detection efficacy, executing controlled attack simulations and achieving 95%+ detection rule accuracy."
  }
];

export const INTERVIEW_CARDS = [
  {
    id: 1,
    domain: "Azure Security",
    question: "How do Azure Private Endpoints differ from Service Endpoints?",
    answer: "Service Endpoints keep traffic on the Azure backbone but keep the service's public IP exposed and grant access at subnet level (data exfiltration risk). Private Endpoints allocate a dedicated Private IP inside your VNet directly to a specific instance of a resource, completely eliminating public network interfaces and enforcing Zero-Trust boundaries."
  },
  {
    id: 2,
    domain: "Azure Security",
    question: "Walk through the exact evaluation order of Azure Network Security Groups (NSGs).",
    answer: "1. Rules evaluated in numerical priority order from 100 to 4096.\n2. Evaluation stops immediately at first match.\n3. Inbound traffic: Subnet NSG evaluated first, then NIC NSG.\n4. Outbound traffic: NIC NSG evaluated first, then Subnet NSG.\n5. NSGs are stateful: if inbound is allowed, return outbound is automatically permitted."
  },
  {
    id: 3,
    domain: "AWS Security",
    question: "Explain IAM policy evaluation logic when SCP, Identity Policy, and Resource Policy collide.",
    answer: "Evaluation engine defaults to Deny. Any explicit Deny overrides all allows. Order: 1. Explicit Deny Check. 2. SCP evaluation. 3. Resource Policy check. 4. Permissions Boundary check. 5. Identity Policy check. Access is granted ONLY if no explicit deny exists AND an explicit allow exists."
  },
  {
    id: 4,
    domain: "DevSecOps",
    question: "How do you prevent sensitive secrets from leaking inside Terraform state files?",
    answer: "Terraform state files store plaintext variables by design. 1. Store state remotely in Azure Blob / AWS S3 encrypted with Customer-Managed Keys (KMS/AKV). 2. Restrict state bucket read access strictly to CI/CD service principals via RBAC. 3. Inject short-lived secrets at runtime via Key Vault or Vault instead of hardcoding in `.tfvars`."
  },
  {
    id: 5,
    domain: "Troubleshooting",
    question: "An App Service cannot connect to Azure SQL after enabling Private Endpoints. How do you debug?",
    answer: "1. Check if VNet Integration is enabled on App Service.\n2. Query DNS inside App Service Kudu console (nameresolver) to check if SQL FQDN resolves to Private IP (10.x.x.x) or Public IP.\n3. Verify Private DNS Zone (privatelink.database.windows.net) is linked to VNet.\n4. Check Subnet NSG for outbound TCP 1433 blocks.\n5. Verify SQL Private Endpoint status is Approved."
  }
];
